/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ThreeRenderer {
        "height": number;
        "updateStyle": boolean;
        "width": number;
    }
}
declare global {
    interface HTMLThreeRendererElement extends Components.ThreeRenderer, HTMLStencilElement {
    }
    var HTMLThreeRendererElement: {
        prototype: HTMLThreeRendererElement;
        new (): HTMLThreeRendererElement;
    };
    interface HTMLElementTagNameMap {
        "three-renderer": HTMLThreeRendererElement;
    }
}
declare namespace LocalJSX {
    interface ThreeRenderer {
        "height"?: number;
        "updateStyle"?: boolean;
        "width"?: number;
    }
    interface IntrinsicElements {
        "three-renderer": ThreeRenderer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "three-renderer": LocalJSX.ThreeRenderer & JSXBase.HTMLAttributes<HTMLThreeRendererElement>;
        }
    }
}
